export enum WadMapThingGroup {
	OTHER = "OTHER",
	MONSTER = "MONSTER",
	POWERUP = "POWERUP",
	ARTIFACT = "ARTIFACT",
	KEY = "KEY",
	WEAPON = "WEAPON",
	AMMO = "AMMO",
	DECORATION = "DECORATION",
	OBSTACLE = "OBSTACLE",
	SPECIAL = "SPECIAL",
	UNKNOWN = "UNKNOWN",
}
