export const playpalLumpName = "PLAYPAL";
export const colormapLumpName = "COLORMAP";
export const endoomLumpName = "ENDOOM";
export const dehackedLumpName = "DEHACKED";
export const texture1LumpName = "TEXTURE1";
export const texture2LumpName = "TEXTURE2";
export const pnamesLumpName = "PNAMES";
export const standaloneTexStartLumpName = "TX_START";
export const standaloneTexEndLumpName = "TX_END";
export const hiresTexStartLumpName = "HI_START";
export const hiresTexEndLumpName = "HI_END";
export const compLvlLumpName = "COMPLVL";
export const musInfoLumpName = "MUSINFO";
export const mapInfoLumpMatcher = /^[A-Za-z]?MAPINFO$/;
export const patchStartLumpMatcher = /^P+\d*_START$/;
export const patchEndLumpMatcher = /^P+\d*_END$/;
export const flatStartLumpMatcher = /^F+\d*_START$/;
export const flatEndLumpMatcher = /^F+\d*_END$/;
export const spriteStartLumpMatcher = /^S+\d*_START$/;
export const spriteEndLumpMatcher = /^S+\d*_END$/;
export const spriteFrameMatcher =
	/^([A-Za-z0-9]{4})([A-Za-z\\\[\]])([0-9A-G])$/;
export const spriteMirroredFrameMatcher =
	/^([A-Za-z0-9]{4})([A-Z])([0-9A-G])[A-Z]([0-9A-G])$/;

export const mapNameMatcher = /^(E[1-9]M[1-9]|MAP[0-9]{1,2}|Map[0-9]{1,2})$/i;
export const globalMapNameMatcher =
	/(E[1-9]M[0-9]{1,2}|MAP[0-9]{1,2}|Map[0-9]{1,2})/;

export const demoMatcher = /^DEMO[0-9]$/;

export const statusBarLumpMatchers: RegExp[] = [
	/STBAR/,
	/STGNUM[0-9]/,
	/STTNUM[0-9]/,
	/STTMINUS/,
	/STTPRCNT/,
	/STYSNUM[0-9]/,
	/STKEYS[0-9]/,
	/AMMNUM[0-9]/,
	/STDISK/,
	/STCDROM/,
	/STARMS/,
	/STF.*/,
	/STP.*/,
	/STCFN.*/,
	/BRDR.*/,
	/LTFACE/,
	/LTFCTOP/,
	/RTFACE/,
	/RTFCTOP/,
	/BARBACK/,
	/CHAINBAC/,
	/CHAIN/,
	/LIFEGEM[0-3]/,
	/ARTIBOX/,
	/SELECTBO/,
	/USEARTI[A-E]/,
	/INVGEMR[1-2]/,
	/STATBAR/,
	/INVBAR/,
	/[A-Z0-9]KEYICON/,
	/BLACKSQ/,
	/ARMCLEAR/,
	/IN[0-9]/,
	/NEGNUM/,
	/LAME/,
	/SMALLIN[0-9]/,
	/INAM.*/,
	/LIFEBAR/,
	/SPINBK.*/,
	/SPFLY.*/,
	/GOD[1-2]/,
	/INVGEML[1-2]/,
	/INRED[0-9]/,
	/SPSHLD.*/,
	/SPBOOT.*/,
	/SPMINO.*/,
	/H2BAR/,
	/H2TOP/,
	/LFEDGE/,
	/RTEDGE/,
	/ARMCLS/,
	/MANAVL[1-2]/,
	/MANABRT[1-2]/,
	/MANAVL[1-2]D/,
	/MANADIM[1-2]/,
	/KILLS/,
	/WPSLOT[0-2]/,
	/WPFULL[0-2]/,
	/WPIECEC[1-3]/,
	/WPIECEM[1-3]/,
	/KEYBAR/,
	/ARMSLOT[1-4]/,
	/CHAIN2/,
	/CHAIN3/,
	/LIFEGEMC[1-8]/,
	/LIFEGEMM[1-8]/,
	/LIFEGEMF[2-8]/,
	/INVBACK/,
	/INVTOP/,
	/INVCURS/,
	/INVPOP/,
	/INVBAK/,
	/INVPOP2/,
	/INVBAK2/,
	/INVFONG[0-9%]/,
	/INVONY[0-9%]/,
	/I_SIG[1-5]/,
	/I_.*/,
	/CBOWA0/,
	/GRNDA0/,
	/RIFLA0/,
	/FLAMA0/,
	/MMSLA0/,
	/TRPDA0/,
];

export const musicLumpNames = [
	"D_INTRO",
	"D_INTROA",
	"D_INTER",
	"D_VICTOR",
	"D_BUNNY",
	"D_E1M1",
	"D_E1M2",
	"D_E1M3",
	"D_E1M4",
	"D_E1M5",
	"D_E1M6",
	"D_E1M7",
	"D_E1M8",
	"D_E1M9",
	"D_E2M1",
	"D_E2M2",
	"D_E2M3",
	"D_E2M4",
	"D_E2M5",
	"D_E2M6",
	"D_E2M7",
	"D_E2M8",
	"D_E2M9",
	"D_E3M1",
	"D_E3M2",
	"D_E3M3",
	"D_E3M4",
	"D_E3M5",
	"D_E3M6",
	"D_E3M7",
	"D_E3M8",
	"D_E3M9",
	"D_DM2TTL",
	"D_DM2INT",
	"D_READ_M",
	"D_RUNNIN",
	"D_STALKS",
	"D_COUNTD",
	"D_BETWEE",
	"D_DOOM",
	"D_THE_DA",
	"D_SHAWN",
	"D_DDTBLU",
	"D_IN_CIT",
	"D_DEAD",
	"D_STLKS2",
	"D_THEDA2",
	"D_DOOM2",
	"D_DDTBL2",
	"D_RUNNI2",
	"D_DEAD2",
	"D_STLKS3",
	"D_ROMERO",
	"D_SHAWN2",
	"D_MESSAG",
	"D_COUNT2",
	"D_DDTBL3",
	"D_AMPIE",
	"D_THEDA3",
	"D_ADRIAN",
	"D_MESSG2",
	"D_ROMER2",
	"D_TENSE",
	"D_SHAWN3",
	"D_OPENIN",
	"D_EVIL",
	"D_ULTIMA",
	"MUS_E1M1",
	"MUS_E1M2",
	"MUS_E1M3",
	"MUS_E1M4",
	"MUS_E1M5",
	"MUS_E1M6",
	"MUS_E1M7",
	"MUS_E1M8",
	"MUS_E1M9",
	"MUS_E2M1",
	"MUS_E2M2",
	"MUS_E2M3",
	"MUS_E2M4",
	"MUS_E2M6",
	"MUS_E2M7",
	"MUS_E2M8",
	"MUS_E2M9",
	"MUS_E3M2",
	"MUS_E3M3",
	"MUS_TITL",
	"MUS_INTR",
	"MUS_CPTD",
	"MUS_HUB1",
	"MUS_HUB2",
	"MUS_HUB3",
	"MUS_HUB4",
];

export const menuGraphicLumpNames: RegExp[] = [
	/HELP[1-2]/,
	/^HELP$/,
	/^BOSSBACK$/,
	/CREDIT$/,
	/TITLEPIC/,
	/INTERPIC/,
	/M_.*/,
	/WIMAP[0-9]/,
	/WIA00.*/,
	/WIURH.*/,
	/WISPLAT/,
	/WIOST.*/,
	/WIF$/,
	/WIMSTT$/,
	/WIOST.*/,
	/WITIME$/,
	/WIPAR$/,
	/WIMSTAR$/,
	/WIMINUS$/,
	/WIPCNT$/,
	/WINUM[0-9]/,
	/WICOLON$/,
	/WISUCKS$/,
	/WIFRGS$/,
	/WILV[0-9]{2}}/,
	/WIP[0-9]/,
	/WIBP[0-9]/,
	/WIKILRS$/,
	/WIVCTMS$/,
	/WISCRT2$/,
	/WIENTER$/,
];
