export interface WadMusic {
	name: string;
	data: Uint8Array;
	type: { ext: string; mime: string };
	inMap: string;
}

export const doomMusicToNameMap: Readonly<Record<string, string>> = {
	D_E1M1: "E1M1: Hangar",
	D_E1M2: "E1M2: Nuclear Plant",
	D_E1M3: "E1M3: Toxin Refinery",
	D_E1M4: "E1M4: Command Control",
	D_E1M5: "E1M5: Phobos Lab",
	D_E1M6: "E1M6: Central Processing",
	D_E1M7: "E1M7: Computer Station",
	D_E1M8: "E1M8: Phobos Anomaly",
	D_E1M9: "E1M9: Military Base",
	D_E2M1: "E2M1: Deimos Anomaly",
	D_E2M2: "E2M2: Containment Area",
	D_E2M3: "E2M3: Refinery",
	D_E2M4: "E2M4: Deimos Lab",
	D_E2M5: "E2M5: Command Center",
	D_E2M6: "E2M6: Halls of the Damned",
	D_E2M7: "E2M7: Spawning Vats",
	D_E2M8: "E2M8: Tower of Babel",
	D_E2M9: "E2M9: Fortress of Mystery",
	D_E3M1: "E3M1: Hell Keep",
	D_E3M2: "E3M2: Slough of Despair",
	D_E3M3: "E3M3: Pandemonium",
	D_E3M4: "E3M4: House of Pain",
	D_E3M5: "E3M5: Unholy Cathedral",
	D_E3M6: "E3M6: Mt. Erebus",
	D_E3M7: "E3M7: Limbo",
	D_E3M8: "E3M8: Dis",
	D_E3M9: "E3M9: Warrens",
	D_E4M1: "E4M1: Hell Beneath",
	D_E4M2: "E4M2: Perfect Hatred",
	D_E4M3: "E4M3: Sever the Wicked",
	D_E4M4: "E4M4: Unruly Evil",
	D_E4M5: "E4M5: They Will Repent",
	D_E4M6: "E4M6: Against Thee Wickedly",
	D_E4M7: "E4M7: And Hell Followed",
	D_E4M8: "E4M8: Unto the Cruel",
	D_E4M9: "E4M9: Fear",
	D_INTER: "Intermission",
	D_INTRO: "Title Screen",
	D_VICTOR: "Victory Music",
	D_BUNNY: "Endgame",
	D_RUNNIN: "MAP01: Entryway",
	D_STALKS: "MAP02: Underhalls",
	D_COUNTD: "MAP03: The Gantlet",
	D_BETWEE: "MAP04: The Focus",
	D_DOOM: "MAP05: The Waste Tunnels",
	D_THE_DA: "MAP06: The Crusher",
	D_SHAWN: "MAP07: Dead Simple",
	D_DDTBLU: "MAP08: Tricks and Traps",
	D_IN_CIT: "MAP09: The Pit",
	D_DEAD: "MAP10: Refueling Base",
	D_STLKS2: "MAP11: Circle of Death",
	D_THEDA2: "MAP12: The Factory",
	D_DOOM2: "MAP13: Downtown",
	D_DDTBL2: "MAP14: The Inmost Dens",
	D_RUNNI2: "MAP15: Industrial Zone",
	D_DEAD2: "MAP16: Suburbs",
	D_STLKS3: "MAP17: Tenements",
	D_ROMERO: "MAP18: The Courtyard",
	D_SHAWN2: "MAP19: The Citadel",
	D_MESSAG: "MAP20: Gotcha!",
	D_COUNT2: "MAP21: Nirvana",
	D_DDTBL3: "MAP22: The Catacombs",
	D_AMPIE: "MAP23: Barrels o' Fun",
	D_THEDA3: "MAP24: The Chasm",
	D_ADRIAN: "MAP25: Bloodfalls",
	D_MESSG2: "MAP26: The Abandoned Mines",
	D_ROMER2: "MAP27: Monster Condo",
	D_TENSE: "MAP28: The Spirit World",
	D_SHAWN3: "MAP29: The Living End",
	D_OPENIN: "MAP30: Icon of Sin",
	D_EVIL: "MAP31: Wolfenstein",
	D_ULTIMA: "MAP32: Grosse",
	D_DM2TTL: "Title Screen",
	D_DM2INT: "Intermission",
	D_READ_M: "Text Screen",
} as const;

export const doomMapIdToMusic: Readonly<Record<string, string>> = {
	E1M1: "D_E1M1",
	E1M2: "D_E1M2",
	E1M3: "D_E1M3",
	E1M4: "D_E1M4",
	E1M5: "D_E1M5",
	E1M6: "D_E1M6",
	E1M7: "D_E1M7",
	E1M8: "D_E1M8",
	E1M9: "D_E1M9",
	E2M1: "D_E2M1",
	E2M2: "D_E2M2",
	E2M3: "D_E2M3",
	E2M4: "D_E2M4",
	E2M5: "D_E2M5",
	E2M6: "D_E2M6",
	E2M7: "D_E2M7",
	E2M8: "D_E2M8",
	E2M9: "D_E2M9",
	E3M1: "D_E3M1",
	E3M2: "D_E3M2",
	E3M3: "D_E3M3",
	E3M4: "D_E3M4",
	E3M5: "D_E3M5",
	E3M6: "D_E3M6",
	E3M7: "D_E3M7",
	E3M8: "D_E3M8",
	E3M9: "D_E3M9",
	E4M1: "D_E4M1",
	E4M2: "D_E4M2",
	E4M3: "D_E4M3",
	E4M4: "D_E4M4",
	E4M5: "D_E4M5",
	E4M6: "D_E4M6",
	E4M7: "D_E4M7",
	E4M8: "D_E4M8",
	E4M9: "D_E4M9",
	MAP01: "D_RUNNIN",
	MAP02: "D_STALKS",
	MAP03: "D_COUNTD",
	MAP04: "D_BETWEE",
	MAP05: "D_DOOM",
	MAP06: "D_THE_DA",
	MAP07: "D_SHAWN",
	MAP08: "D_DDTBLU",
	MAP09: "D_IN_CIT",
	MAP10: "D_DEAD",
	MAP11: "D_STLKS2",
	MAP12: "D_THEDA2",
	MAP13: "D_DOOM2",
	MAP14: "D_DDTBL2",
	MAP15: "D_RUNNI2",
	MAP16: "D_DEAD2",
	MAP17: "D_STLKS3",
	MAP18: "D_ROMERO",
	MAP19: "D_SHAWN2",
	MAP20: "D_MESSAG",
	MAP21: "D_COUNT2",
	MAP22: "D_DDTBL3",
	MAP23: "D_AMPIE",
	MAP24: "D_THEDA3",
	MAP25: "D_ADRIAN",
	MAP26: "D_MESSG2",
	MAP27: "D_ROMER2",
	MAP28: "D_TENSE",
	MAP29: "D_SHAWN3",
	MAP30: "D_OPENIN",
	MAP31: "D_EVIL",
	MAP32: "D_ULTIMA",
} as const;

export const dehackedLevelTextToMusicId: Readonly<Record<string, string>> = {
	"level 1: entryway": "D_RUNNIN",
	"level 2: underhalls": "D_STALKS",
	"level 3: the gantlet": "D_COUNTD",
	"level 4: the focus": "D_BETWEE",
	"level 5: the waste tunnels": "D_DOOM",
	"level 6: the crusher": "D_THE_DA",
	"level 7: dead simple": "D_SHAWN",
	"level 8: tricks and traps": "D_DDTBLU",
	"level 9: the pit": "D_IN_CIT",
	"level 10: refueling base": "D_DEAD",
	"level 11: 'o' of destruction!": "D_STLKS2",
	"level 12: the factory": "D_THEDA2",
	"level 13: downtown": "D_DOOM2",
	"level 14: the inmost dens": "D_DDTBL2",
	"level 15: industrial zone": "D_RUNNI2",
	"level 16: suburbs": "D_DEAD2",
	"level 17: tenements": "D_STLKS3",
	"level 18: the courtyard": "D_ROMERO",
	"level 19: the citadel": "D_SHAWN2",
	"level 20: gotcha!": "D_MESSAG",
	"level 21: nirvana": "D_COUNT2",
	"level 22: the catacombs": "D_DDTBL3",
	"level 23: barrels o' fun": "D_AMPIE",
	"level 24: the chasm": "D_THEDA3",
	"level 25: bloodfalls": "D_ADRIAN",
	"level 26: the abandoned mines": "D_MESSG2",
	"level 27: monster condo": "D_ROMER2",
	"level 28: the spirit world": "D_TENSE",
	"level 29: the living end": "D_SHAWN3",
	"level 30: icon of sin": "D_OPENIN",
	"level 31: wolfenstein": "D_EVIL",
	"level 32: grosse": "D_ULTIMA",
} as const;
