export interface WadMusic {
	name: string;
	data: Uint8Array;
	type: { ext: string; mime: string };
	inMap: string;
}

export const doomMusicToNameMap: Readonly<Record<string, string>> = {
	D_E1M1: "Hangar (E1M1)",
	D_E1M2: "Nuclear Plant (E1M2)",
	D_E1M3: "Toxin Refinery (E1M3)",
	D_E1M4: "Command Control (E1M4)",
	D_E1M5: "Phobos Lab (E1M5)",
	D_E1M6: "Central Processing (E1M6)",
	D_E1M7: "Computer Station (E1M7)",
	D_E1M8: "Phobos Anomaly (E1M8)",
	D_E1M9: "Military Base (E1M9)",
	D_E2M1: "Deimos Anomaly (E2M1)",
	D_E2M2: "Containment Area (E2M2)",
	D_E2M3: "Refinery (E2M3)",
	D_E2M4: "Deimos Lab (E2M4)",
	D_E2M5: "Command Center (E2M5)",
	D_E2M6: "Halls of the Damned (E2M6)",
	D_E2M7: "Spawning Vats (E2M7)",
	D_E2M8: "Tower of Babel (E2M8)",
	D_E2M9: "Fortress of Mystery (E2M9)",
	D_E3M1: "Hell Keep (E3M1)",
	D_E3M2: "Slough of Despair (E3M2)",
	D_E3M3: "Pandemonium (E3M3)",
	D_E3M4: "House of Pain (E3M4)",
	D_E3M5: "Unholy Cathedral (E3M5)",
	D_E3M6: "Mt. Erebus (E3M6)",
	D_E3M7: "Limbo (E3M7)",
	D_E3M8: "Dis (E3M8)",
	D_E3M9: "Warrens (E3M9)",
	D_E4M1: "Hell Beneath (E4M1)",
	D_E4M2: "Perfect Hatred (E4M2)",
	D_E4M3: "Sever the Wicked (E4M3)",
	D_E4M4: "Unruly Evil (E4M4)",
	D_E4M5: "They Will Repent (E4M5)",
	D_E4M6: "Against Thee Wickedly (E4M6)",
	D_E4M7: "And Hell Followed (E4M7)",
	D_E4M8: "Unto the Cruel (E4M8)",
	D_E4M9: "Fear (E4M9)",
	D_INTER: "Intermission",
	D_INTRO: "Title Screen",
	D_VICTOR: "Victory Music",
	D_BUNNY: "Endgame",
	D_RUNNIN: "Entryway (MAP01)",
	D_STALKS: "Underhalls (MAP02)",
	D_COUNTD: "The Gantlet (MAP03)",
	D_BETWEE: "The Focus (MAP04)",
	D_DOOM: "The Waste Tunnels (MAP05)",
	D_THE_DA: "The Crusher (MAP06)",
	D_SHAWN: "Dead Simple (MAP07)",
	D_DDTBLU: "Tricks and Traps (MAP08)",
	D_IN_CIT: "The Pit (MAP09)",
	D_DEAD: "Refueling Base (MAP10)",
	D_STLKS2: "Circle of Death (MAP11)",
	D_THEDA2: "The Factory (MAP12)",
	D_DOOM2: "Downtown (MAP13)",
	D_DDTBL2: "The Inmost Dens (MAP14)",
	D_RUNNI2: "Industrial Zone (MAP15)",
	D_DEAD2: "Suburbs (MAP16)",
	D_STLKS3: "Tenements (MAP17)",
	D_ROMERO: "The Courtyard (MAP18)",
	D_SHAWN2: "The Citadel (MAP19)",
	D_MESSAG: "Gotcha! (MAP20)",
	D_COUNT2: "Nirvana (MAP21)",
	D_DDTBL3: "The Catacombs (MAP22)",
	D_AMPIE: "Barrels o' Fun (MAP23)",
	D_THEDA3: "The Chasm (MAP24)",
	D_ADRIAN: "Bloodfalls (MAP25)",
	D_MESSG2: "The Abandoned Mines (MAP26)",
	D_ROMER2: "Monster Condo (MAP27)",
	D_TENSE: "The Spirit World (MAP28)",
	D_SHAWN3: "The Living End (MAP29)",
	D_OPENIN: "Icon of Sin (MAP30)",
	D_EVIL: "Wolfenstein (MAP31)",
	D_ULTIMA: "Grosse (MAP32)",
	D_DM2TTL: "Title Screen",
	D_DM2INT: "Intermission",
	D_READ_M: "Text Screen",
} as const;
